# Streamlit configuration file

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = true

[logger]
level = "info"

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 